docs(readme): add root readme

diff --git a/cli b/cli
--- a/cli
+++ b/cli
@@ -1,7 +1,10 @@
 #!/bin/bash
 
 PACKAGE_FOLDER=packages
+CONTAINER_NAME=monorepo
+WORKSPACE_ONLY=
 
+VERSION=v1.0.2
 SEPERATOR="------------------------"
 
 trap trap_int INT
@@ -9,31 +12,35 @@ function trap_int() {
   echo -e "${SEPERATOR}\n[interrupt] ${PACKAGE_INFO}"
 }
 
-echo "[monorepo] Run in Docker"
-echo "${SEPERATOR}"
+echo -e "[monorepo] Run in Docker ${VERSION}\n${SEPERATOR}"
 
 # throw default error
-if [ -z "$1" ]; then
-  echo "Please state a package folder relative to '${PACKAGE_FOLDER}'."
+if [ -z "$1" ] && [ -z "${WORKSPACE_ONLY}" ]; then
+  echo "[error] Please state a package folder relative to '${PACKAGE_FOLDER}'."
   exit 127
 fi
 
 # ls command
-if [ "$1" == "ls" ]; then
+if [ "$1" == "ls" ] && [ -z "$WORKSPACE_ONLY" ]; then
   npx lerna la
   exit 0
 fi
 
 # check command
-PACKAGES=$(npx lerna la)
-PACKAGE=($(echo ${PACKAGES} | grep $1 | sed -r 's/^([^ ]*).*$/\1/'))
 
-IS_WORKSPACE=$([[ "$1" == "root" || "$1" == "ws" ]] && echo true)
-IS_FORALL=$([[ "$1" == "all" ]] && echo true)
-IS_LERNA=$([[ "$1" == "lerna" ]] && echo true)
+if [ -z "$WORKSPACE_ONLY" ]; then
+  PACKAGES=$(npx lerna la)
+  PACKAGE=($(echo ${PACKAGES} | grep $1 | sed -r 's/^([^ ]*).*$/\1/'))
+
+  IS_WORKSPACE=$([[ "$1" == "root" || "$1" == "ws" || "$1" == "." ]] && echo true)
+  IS_FORALL=$([[ "$1" == "all" ]] && echo true)
+  IS_LERNA=$([[ "$1" == "lerna" ]] && echo true)
+else
+  IS_WORKSPACE=true
+fi
 
 if [[ -z "${PACKAGE}" && -z "${IS_WORKSPACE}" && -z "${IS_FORALL}" && -z "${IS_LERNA}" ]]; then
-  echo "Can not find package in directory."
+  echo "[error] Can not find package in directory."
   echo "${SEPERATOR}"
   echo "Available packages are:"
   echo "${PACKAGES}"
@@ -49,12 +56,16 @@ else
 fi
 
 # command
-if [ ! -z "${IS_FORALL}" ]; then
-  RUN_COMMAND="npx lerna exec -- ${*:2}"
-elif [ ! -z "${IS_LERNA}" ]; then
-  RUN_COMMAND="npx lerna ${*:2}"
+if [ -z "${WORKSPACE_ONLY}" ]; then
+  if [ ! -z "${IS_FORALL}" ]; then
+    RUN_COMMAND="npx lerna exec -- ${*:2}"
+  elif [ ! -z "${IS_LERNA}" ]; then
+    RUN_COMMAND="npx lerna ${*:2}"
+  else
+    RUN_COMMAND="${*:2}"
+  fi
 else
-  RUN_COMMAND="${*:2}"
+  RUN_COMMAND="${*:1}"
 fi
 
 if [ -z "${RUN_COMMAND}" ]; then
@@ -63,4 +74,4 @@ if [ -z "${RUN_COMMAND}" ]; then
 fi
 
 PACKAGE_INFO="${PACKAGE} in ${WORKDIR} | \$ ${RUN_COMMAND}"
-docker-compose exec monorepo /bin/bash -c "echo -e '[started] ${PACKAGE_INFO}\n${SEPERATOR}' && cd ${WORKDIR} && ${RUN_COMMAND} && echo -e '${SEPERATOR}\n[success] ${PACKAGE_INFO}' || echo -e '${SEPERATOR}\n[failed] ${PACKAGE_INFO}'"
+docker-compose exec ${CONTAINER_NAME} /bin/bash -c "echo -e '[started] ${PACKAGE_INFO}\n${SEPERATOR}' && cd ${WORKDIR} && ${RUN_COMMAND} && echo -e '${SEPERATOR}\n[success] ${PACKAGE_INFO}' || echo -e '${SEPERATOR}\n[failed] ${PACKAGE_INFO}'"
